---
# tasks file for donfilemon.named
- name: Install Packges 
  yum:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - bind
    - bind-utils
- name: Copy named.conf file
  template: 
    src: named.conf.j2 
    dest: /etc/named.conf
    backup: yes
  register: nameconf
- name: Copy forward.zone file
  template: 
    src: template.forward.j2 
    dest: /var/named/{{ forward_zone }}db
    backup: yes
  register: forwardzone
- name: Start service named if not started and enable autostart 
  service:
    name: named
    state: started
    enabled: yes
- name: Restart service ntpd, in all cases
  service:
    name: named
    state: restarted
  # when: conf.changed